[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="currentUser" type="ru.kpfu.itis.gymapp.models.User" --]
[#-- @ftlvariable name="errors" type="java.util.List<org.springframework.validation.ObjectError>" --]
[#-- @ftlvariable name="user" type="ru.kpfu.itis.gymapp.models.User" --]
